//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contramcamlamroi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Required(ErrorMessage = "ID Không được trống!")]
        [Display(Name = "Mã Tài Khoản")]
        public int ID { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập không được trống!")]
        [Display(Name = "Tên Tài Khoản")]
        public string NameUser { get; set; }
        [DisplayName("Vị Trí")]
        public string RoleUser { get; set; }
        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu không được trống!")]
        public string PasswordUser { get; set; }
        [NotMapped]
        [Compare("PasswordUser")]
        [DisplayName("Nhập lại mật khấu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }
    }

}
