//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contramcamlamroi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }

        public int IDCus { get; set; }
        public string NameCus { get; set; }
        [Required(ErrorMessage = "Số Điện Thoại Không Được Trống")]
        [RegularExpression(@"^([0])?[1-9][0-9]{8}$",ErrorMessage = "Số Điện Thoại Không Hợp Lệ")]

        public string PhoneCus { get; set; }
        [Required(ErrorMessage = "Field can't be empty")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail không hợp lệ")]
        public string EmailCus { get; set; }

        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
